In [2]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import mpltw
import matplotlib.pyplot as plt
import seaborn as sns
#plt.style.use('seaborn')
from Sales_Pipeline import pipeline, user_item_matrix
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
sales_1 = pd.read_excel('../iCheers_data_new/iCheers銷售記錄(2021).xlsx')
sales_2 = pd.read_excel('../iCheers_data_new/iCheers銷售記錄(2022).xlsx')
item = pd.read_excel('../iCheers_data_new/iCheers酒款資料.xlsx')
grape = pd.read_excel('../iCheers_data_new/iCheers品種.xlsx')
users = pd.read_excel('../iCheers_data_new/iCheers客戶資料.xlsx')

#資料預處理
grape = grape.groupby('上架編號').agg({'品種': lambda x: '+'.join(list(x))})
sales_1 = pipeline(sales_1, item, grape)
sales_2 = pipeline(sales_2, item, grape)
sales = pd.concat([sales_1, sales_2], axis=0)
area = '細區' #目前只能用細區
criteria = '銷貨數量' #只會影響相似度的計算
UI_mat = user_item_matrix(sales, area=area, criteria=criteria)

In [50]:
UI_mat

細區                                以色列戈蘭高地加利利   以色列戈蘭高地加利利白  以色列戈蘭高地加利利紅  \
客戶代碼                                                                      
000354fe836b0f0d385ab4c07ff0ac17          0.0          0.0          0.0   
0007484d651c9a8127ac33a505f37fd1          0.0          0.0          0.0   
000b865d608f7c0137c72cf8f00e3559          0.0          0.0          0.0   
001734fefec772f1814d89d4141460c7          0.0          0.0          0.0   
00178e471d27295a13f0f961325e28c4          0.0          0.0          0.0   
...                                       ...          ...          ...   
fff2f7701c2616bb5d66a0feb6336fbf          0.0          0.0          0.0   
fff6098244d0bbcd94e1888fd4648a76          0.0          0.0          0.0   
fff7caa578aa7e7134ccf687f7c2d3c2          0.0          0.0          0.0   
fffc530c3ecffc53a0c018fab14e5475          0.0          0.0          0.0   
fffccd0debf95257c380505a6491a2b5          0.0          0.0          0.0   

細區                                匈牙利Eger 白  匈牙利Somlo 白  匈牙利Villany 白  \
客戶代碼                                                                    
000354fe836b0f0d385ab4c07ff0ac17        0.0         0.0           0.0   
0007484d651c9a8127ac33a505f37fd1        0.0         0.0           0.0   
000b865d608f7c0137c72cf8f00e3559        0.0         0.0           0.0   
001734fefec772f1814d89d4141460c7        0.0         0.0           0.0   
00178e471d27295a13f0f961325e28c4        0.0         0.0           0.0   
...                                     ...         ...           ...   
fff2f7701c2616bb5d66a0feb6336fbf        0.0         0.0           0.0   
fff6098244d0bbcd94e1888fd4648a76        0.0         0.0           0.0   
fff7caa578aa7e7134ccf687f7c2d3c2        0.0         0.0           0.0   
fffc530c3ecffc53a0c018fab14e5475        0.0         0.0           0.0   
fffccd0debf95257c380505a6491a2b5        0.0         0.0           0.0   

細區                                匈牙利Villany 粉紅  匈牙利Villany 紅  匈牙利托凱 琥珀色  \
客戶代碼                                                                       
000354fe836b0f0d385ab4c07ff0ac17            0.0           0.0        0.0   
0007484d651c9a8127ac33a505f37fd1            0.0           0.0        0.0   
000b865d608f7c0137c72cf8f00e3559            0.0           0.0        0.0   
001734fefec772f1814d89d4141460c7            0.0           0.0        0.0   
00178e471d27295a13f0f961325e28c4            0.0           0.0        0.0   
...                                         ...           ...        ...   
fff2f7701c2616bb5d66a0feb6336fbf            0.0           0.0        0.0   
fff6098244d0bbcd94e1888fd4648a76            0.0           0.0        0.0   
fff7caa578aa7e7134ccf687f7c2d3c2            0.0           0.0        0.0   
fffc530c3ecffc53a0c018fab14e5475            0.0           0.0        0.0   
fffccd0debf95257c380505a6491a2b5            0.0           0.0        0.0   

細區                                匈牙利托凱 白  ...  阿根廷門多薩San Carlos紅  \
客戶代碼                                       ...                      
000354fe836b0f0d385ab4c07ff0ac17      0.0  ...                0.0   
0007484d651c9a8127ac33a505f37fd1      0.0  ...                0.0   
000b865d608f7c0137c72cf8f00e3559      0.0  ...                0.0   
001734fefec772f1814d89d4141460c7      0.0  ...                0.0   
00178e471d27295a13f0f961325e28c4      0.0  ...                0.0   
...                                   ...  ...                ...   
fff2f7701c2616bb5d66a0feb6336fbf      0.0  ...                0.0   
fff6098244d0bbcd94e1888fd4648a76      0.0  ...                0.0   
fff7caa578aa7e7134ccf687f7c2d3c2      0.0  ...                0.0   
fffc530c3ecffc53a0c018fab14e5475      0.0  ...                0.0   
fffccd0debf95257c380505a6491a2b5      0.0  ...                0.0   

細區                                阿根廷門多薩Santa Rosa紅  阿根廷門多薩Tunuyan紅  \
客戶代碼                                                                  
000354fe836b0f0d385ab4c07ff0ac17             

In [11]:
def top_n_recommendations_for_user(r_hat, user, n=10):
    # 檢查用戶是否在DataFrame中
    if user not in r_hat.index:
        return None  # 或者返回一個適當的信息，比如"用戶未找到"
    
    # Get the user's rating predictions
    user_ratings = r_hat.loc[user, :]
    
    # Find the indices of the top N ratings
    top_n_indices = np.argsort(-user_ratings.values)[:n]  # 使用.values將其轉化為numpy數組
    
    # Get the top N ratings using the indices
    top_n_ratings = user_ratings.iloc[top_n_indices]
    
    top_n_ratings = [(name, float(score)) for name, score in top_n_ratings.items()]
    
    return top_n_ratings

In [12]:
def oringinal_top_n_recommendations_for_user(r_hat, user, n=10):
    # 檢查用戶是否在DataFrame中
    if user not in r_hat.index:
        return None  # 或者返回一個適當的信息，比如"用戶未找到"
    
    # Get the user's rating predictions
    user_ratings = r_hat.loc[user, :]
    user_ratings = user_ratings[user_ratings>0]
    
    # Find the indices of the top N ratings
    top_n_indices = np.argsort(-user_ratings.values)[:n]  # 使用.values將其轉化為numpy數組
    
    # Get the top N ratings using the indices
    top_n_ratings = user_ratings.iloc[top_n_indices]
    
    top_n_ratings = [(name, float(score)) for name, score in top_n_ratings.items()]
    
    return top_n_ratings

In [13]:
def predict_results(predicted_ratings, UI_mat = UI_mat):
    # Define the user for whom we want to make predictions
    picked_user_list = ['231228b77124b1331fbee2abfc9cf923', 'afb8a6cf419846dccdaca13bb275de65', '3b9abfef5b9dbfd31c664470dc528319',
                     'b1f7077b077152c4f004c7180a59c2e8', 'a789b30e0893ab3d4fcdceb18e46a782', '723b7787cb8db4e2d5ff7dee3af65a49']
                        
    for i in picked_user_list:
        print(i)
        top_n_recommendations = top_n_recommendations_for_user(predicted_ratings, i, n=10)
        print("這是預測的最高前10個")
        print(top_n_recommendations)
        # Get the top N recommendations
        top_n_recommendations = oringinal_top_n_recommendations_for_user(UI_mat, i, n=10)
        print("這是原本最高的前10個")
        print(top_n_recommendations)
        print("\n")

### 2.2.1 NMF

In [23]:
from sklearn.decomposition import NMF

model = NMF(n_components=50, init='random', random_state=0)

# 拟合数据并转换
W = model.fit_transform(UI_mat)  
H = model.components_            

predicted_ratings = np.dot(W, H)
predicted_ratings = pd.DataFrame(predicted_ratings, index= UI_mat.index,columns=UI_mat.columns)
predict_results(predicted_ratings)

231228b77124b1331fbee2abfc9cf923
這是預測的最高前10個
[('法國布根地 白', 4.941134786265802), ('法國布根地 紅', 0.9944673727741954), ('法國布根地夏布利白', 0.9554422019623809), ('美國加州北海岸白', 0.9459003463639301), ('法國隆河谷隆河丘白', 0.37512103895876386), ('法國隆河谷 白', 0.22037892373290366), ('法國布根地夜丘白', 0.14453693478802923), ('法國布根地夏隆內丘白', 0.14153358870272556), ('法國波爾多 白', 0.13815092445870386), ('法國波爾多索甸白', 0.10254988410974758)]
這是原本最高的前10個
[('法國布根地 白', 5.0), ('法國布根地 紅', 1.0), ('法國布根地夏布利白', 1.0), ('美國加州北海岸白', 1.0)]


afb8a6cf419846dccdaca13bb275de65
這是預測的最高前10個
[('法國布根地 紅', 10.070089560307038), ('法國隆河谷隆河丘紅', 8.14281274519138), ('法國香檳 白', 7.03819356661153), ('法國波爾多波雅克紅', 7.006703902079315), ('澳洲南澳巴羅沙谷紅', 6.91695997748518), ('法國布根地上夜丘紅', 6.143341435050479), ('美國加州 白', 6.094880298976093), ('西班牙利奧哈上利奧哈紅', 5.841532503890232), ('法國布根地夜丘紅', 5.4466727133147455), ('法國布根地 白', 5.23222281558653)]
這是原本最高的前10個
[('黎巴嫩  紅', 11.0), ('法國布根地 紅', 10.0), ('法國隆河谷隆河丘紅', 8.0), ('法國香檳 白', 7.0), ('澳洲南澳巴羅沙谷紅', 7.0), ('法國波爾多波雅克紅', 7.0), ('美國加州 白', 6.0), 

### 2.2.2 SVD++

In [3]:
import pandas as pd
from surprise import SVDpp, Dataset, Reader
from surprise.model_selection import GridSearchCV, cross_validate, train_test_split
from surprise import accuracy


data_transform_temp = UI_mat.reset_index().melt(id_vars=['客戶代碼'], var_name='細區', value_name='rating')
data_transform = data_transform_temp[data_transform_temp['rating']!=0]

print(data_transform["rating"].max())
print(data_transform['rating'].min())
reader = Reader(rating_scale=(1, 420))
data = Dataset.load_from_df(data_transform_temp[['客戶代碼', '細區', 'rating']], reader)

420.0
1.0


In [4]:
import pandas as pd

data_transform.rename(columns={'客戶代碼': 'user_id:token', '細區': 'item_id:token', 'rating':'rating:float'}, inplace=True)
data_transform['user_id:token'] = data_transform['user_id:token'].astype(str).str.replace('"', '').str.replace(' ', '_')
data_transform['item_id:token'] = data_transform['item_id:token'].astype(str).str.replace('"', '').str.replace(' ', '_')
data_transform['rating:float'] = data_transform['rating:float'].astype(float)
data_transform.to_csv('./icheers/icheers.inter', sep='\t', index=False)
# data_transform.rename(columns={'客戶代碼': 'user_id', '細區': 'item_id', 'rating':'rating'}, inplace=True)
# data_transform.to_csv('./my_dataset/my_dataset.inter', sep=' ', index=False)

In [ ]:
param_grid = {
    'n_epochs': [20, 50, 100], 
    'lr_all': [0.005, 0.01, 0.1],
    'n_factors': [50,100, 200, 300],
    'reg_all': [0.02, 0.05]
}

gs = GridSearchCV(SVDpp, param_grid, measures=['rmse'], cv=3)
gs.fit(data)

print('Best RMSE:', gs.best_score['rmse'])
print('Best parameters:', gs.best_params['rmse'])

In [ ]:
algo = SVDpp(n_epochs=gs.best_params['rmse']['n_epochs'], 
             lr_all=gs.best_params['rmse']['lr_all'],
             n_factors=gs.best_params['rmse']['n_factors'],
             reg_all=gs.best_params['rmse']['reg_all'])

trainset = data.build_full_trainset()
algo.fit(trainset)

In [ ]:
train_set, val_set = train_test_split(data, test_size=.3)
model = SVDpp()
model.fit(train_set)

In [16]:
all_users = data_transform_temp['客戶代碼'].unique()
all_items = data_transform_temp['細區'].unique()

predictions = []

for user in all_users:
    for item in all_items:
        pred = model.predict(user, item)
        predictions.append([user, item, pred.est])

df_predictions = pd.DataFrame(predictions, columns=['客戶代碼', '細區', 'rating'])
pivot_table = df_predictions.pivot(index='客戶代碼', columns='細區', values='rating')

### Another SVD++ model

In [ ]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import mpltw
import matplotlib.pyplot as plt
import seaborn as sns
#plt.style.use('seaborn')
from Sales_Pipeline import pipeline, user_item_matrix
from sklearn.metrics.pairwise import cosine_similarity

user_area = UI_mat.values
user_area_mean = user_area.mean()

user_area_centered = user_area - user_area_mean
user_area_centered_df = pd.DataFrame(user_area_centered, index= UI_mat.index, columns= UI_mat.columns)

# set initial status
b_user = np.zeros(UI_mat.shape[0])
b_item = np.zeros(UI_mat.shape[1])
row_num = UI_mat.shape[0]
column_num = UI_mat.shape[1]
threshold = 1e-6
max_iterations = 100
alpha = 0.01
lambda_ = 0.02
J_init = float('inf')
iteration = 0
converged = False

# update
while iteration < max_iterations and not converged:
    current_J = 0
    
    for i in range(row_num):
        for j in range(column_num):
            #calculate error
            e_ij = user_area_centered[i][j] - b_user[i] - b_item[j]
            
            #update b_user and b_item
            b_user[i] += alpha * (e_ij - (lambda_ * b_user[i]))
            b_item[j] += alpha * (e_ij - (lambda_ * b_item[j]))
            
            current_J += e_ij**2
            
    current_J += lambda_ /2 * ((np.sum(b_user**2)) + np.sum(b_item**2))
    
    if abs(J_init - current_J) < threshold:
        converged = True
    else:
        J_init = current_J
        iteration += 1
    
B_ij = np.array([[x+y for y in b_item] for x in b_user])

item_similarity = cosine_similarity(UI_mat.T)
item_similarity_df = pd.DataFrame(item_similarity, index= UI_mat.columns, columns=UI_mat.columns)

ratings_np = np.around(user_area_centered_df.to_numpy(),2)
similarity_np = np.around(item_similarity_df.to_numpy(),2)
UI_mat_np = np.around(UI_mat.to_numpy(),4)
ratings_np[np.isnan(ratings_np)] = 0
similarity_np[np.isnan(similarity_np)] = 0

# Number of latent factors
latent_factor = 2

w_item_np = np.around(np.random.rand(ratings_np.shape[1], ratings_np.shape[1]) * 1, 4)
c_lj_np = np.around(np.random.rand(ratings_np.shape[1], ratings_np.shape[1]) * 1, 4)
B_il_np = np.around(B_ij,4)
U_np = np.around(np.random.rand(ratings_np.shape[0], latent_factor + 2) * 1,4)
V_np = np.around(np.random.rand(ratings_np.shape[1], latent_factor + 2) * 1,4)
Y_np = np.around(np.random.rand(ratings_np.shape[1], latent_factor + 2) * 1,4)
r_hat_np = np.ones((ratings_np.shape[0], ratings_np.shape[1]))

U_np[:, -2] = 1  
V_np[:, -1] = 1 
Y_np[:, -2:] = 0

# Parameters
alpha_1 = 0.00001
alpha_2  = 0.00001
lambda_1 = 0.00001
lambda_2 = 0.00001

K = 10

def calculate_sum_Yhs_over_sqrt_Ii_np(ratings_np, user_index, Y_np):
    non_zero_indices = ratings_np[user_index, :] > 0
    num_non_zero_ratings = non_zero_indices.sum()
    if num_non_zero_ratings == 0:
        return 0

    sum_Yhs_columns = np.around(np.sum(Y_np[non_zero_indices], axis=0),decimals=4)
    # Clip the values to prevent overflow before division
    sum_Yhs_columns = np.clip(sum_Yhs_columns, -1e4, 1e4)
    # Limit the precision to avoid overflow issues
    sum_Yhs_columns = np.around(sum_Yhs_columns, decimals=4)
    
    sqrt_non_zero_indices = np.around(np.sqrt(num_non_zero_ratings),decimals=4)
    final_sum_Yhs = np.around(sum_Yhs_columns / sqrt_non_zero_indices, decimals=4)
    Y_sum = np.around(np.sum(final_sum_Yhs), decimals=4)
    return Y_sum

def predict_rating_np(U_np, V_np, Y_np, user_index, item_index, w_item_np, B_il_np, c_lj_np, latent_factor, K):
    neighbors_indices = np.argsort(-similarity_np[item_index])[:K]
    neighbors_ratings = ratings_np[user_index, neighbors_indices]
    neighbors_biases = B_il_np[user_index, neighbors_indices]
    sqrt_neighbor_len = np.around(np.sqrt(len(neighbors_indices)),decimals=2)
    
    sum_part_first = np.around(np.sum(w_item_np[item_index, neighbors_indices] * (neighbors_ratings - neighbors_biases)), decimals=4)
    
    sum_part_last = np.around(np.sum(c_lj_np[neighbors_indices, item_index]), decimals=4)
    
    if sqrt_neighbor_len == 0:
        sum_part_neighbor = 0
    else:
        sum_part_neighbor = np.around(((sum_part_first + sum_part_last) / sqrt_neighbor_len), decimals=4)
    sum_part_neighbor = np.around(sum_part_neighbor, decimals=4)

    Y_sum = calculate_sum_Yhs_over_sqrt_Ii_np(ratings_np, user_index, Y_np)
    Y_sum = np.around(Y_sum, decimals=4)
    sum_part_latent = np.around(np.dot(U_np[user_index, :latent_factor + 2] + Y_sum, V_np[item_index, :latent_factor + 2]), decimals=4)
    prediction = sum_part_neighbor + sum_part_latent
    prediction = np.around(prediction, decimals=4)
    
    return prediction, Y_sum

def sgd_step_np(U_np, V_np, Y_np, w_item_np, B_il_np, ratings_np, similarity_np, alpha_1, alpha_2, lambda_1, lambda_2, K, c_lj_np, latent_factor):
    U_np = np.nan_to_num(U_np)
    V_np = np.nan_to_num(V_np)
    Y_np = np.nan_to_num(Y_np)
    ratings_np = np.nan_to_num(ratings_np)
    similarity_np = np.nan_to_num(similarity_np)
    B_il_np = np.nan_to_num(B_il_np)
    
    users, items = np.nonzero(ratings_np)
    
    for user_index, item_index in zip(users, items):
        prediction, Y_sum = predict_rating_np(U_np, V_np, Y_np, user_index, item_index, w_item_np, B_il_np, c_lj_np, latent_factor, K)
        error = np.around((ratings_np[user_index, item_index] - prediction), decimals=4)
        
        # Validate prediction and error to avoid NaN propagation
        if np.isnan(prediction) or np.isinf(prediction) or np.isnan(error) or np.isinf(error):
            error = 0
        
        rated_indices = ratings_np[user_index, :] > 0
        sqrt_Iu = np.sqrt(np.sum(rated_indices))
        sqrt_Iu = np.around(sqrt_Iu, decimals=4)
        
        # Update U
        U_update = np.around(alpha_1 * (error * V_np[item_index, :] - lambda_1 * U_np[user_index, :]),decimals=4)
        U_np[user_index, :] += np.around(np.nan_to_num(U_update), decimals=4)
        
        # Calculate Y's sum and update V
        if sqrt_Iu > 0:
            V_update = np.around(alpha_1 * (error * (U_np[user_index, :] + Y_sum) - lambda_1 * V_np[item_index, :]),decimals=4)
            V_np[item_index, :] += np.around(np.nan_to_num(V_update), decimals=4)

        # Update Y

        if sqrt_Iu == 0:
            Y_update = np.around((alpha_1) * ( - lambda_1 * Y_np[rated_indices, :]), decimals=4)
            Y_np[rated_indices, :] += np.around(np.nan_to_num(Y_update), decimals=4)
            
        else:
            Y_update = np.around((alpha_1) * ( np.around((error * V_np[item_index, :] / sqrt_Iu),decimals=4) - lambda_1 * Y_np[rated_indices, :]), decimals=4)
            Y_np[rated_indices, :] += np.around(np.nan_to_num(Y_update), decimals=4)
            
        neighbors_indices = np.argsort(-similarity_np[item_index, :])[:K]
        neighbors_indices = neighbors_indices[ratings_np[user_index, neighbors_indices] > 0]
        sqrt_neighbor_len = np.around(np.sqrt(len(neighbors_indices)), decimals=4)
    
        if sqrt_neighbor_len == 0:
            
            w_item_update = np.around(alpha_2 * ( - lambda_2 * w_item_np[item_index, neighbors_indices]),decimals=4)
            w_item_np[item_index, neighbors_indices] += np.around(np.nan_to_num(w_item_update),decimals=4)
            
            c_lj_update = np.around(alpha_2 * (- lambda_2 * c_lj_np[neighbors_indices, item_index]),decimals=4)
            c_lj_np[neighbors_indices, item_index] += np.around(np.nan_to_num(c_lj_update),decimals=4)
        else:
            w_item_update = np.around(alpha_2 * np.around(((error * (ratings_np[user_index, neighbors_indices] - B_il_np[user_index, neighbors_indices]) / sqrt_neighbor_len) - lambda_2 * w_item_np[item_index, neighbors_indices]), decimals=4), decimals=4)
            w_item_np[item_index, neighbors_indices] += np.around(np.nan_to_num(w_item_update), decimals=4)
            
            c_lj_update = np.around(alpha_2 * ((error / sqrt_neighbor_len) - lambda_2 * c_lj_np[neighbors_indices, item_index]),decimals=4)
            c_lj_np[neighbors_indices, item_index] += np.around(np.nan_to_num(c_lj_update),decimals=4)
        
        U_np[:, -2] = 1  
        V_np[:, -1] = 1 
        Y_np[:, -2:] = 0

        
    return U_np, V_np, Y_np, w_item_np, c_lj_np

for _ in range(100):
    U_np, V_np, Y_np, w_item_np, c_lj_np = sgd_step_np(
        U_np, V_np, Y_np, w_item_np, B_il_np, ratings_np, similarity_np, 
        alpha_1, alpha_2, lambda_1, lambda_2, K, c_lj_np, latent_factor)

    U_np = np.nan_to_num(U_np)
    V_np = np.nan_to_num(V_np)
    Y_np = np.nan_to_num(Y_np)
    ratings_np = np.nan_to_num(ratings_np)
    similarity_np = np.nan_to_num(similarity_np)
    B_il_np = np.nan_to_num(B_il_np)
    c_lj_np = np.nan_to_num(c_lj_np)
    
def predict_all_ratings_np(ratings_np, U_np, V_np, Y_np, w_item_np, B_il_np, c_lj_np, latent_factor, K):
    num_users, num_items = ratings_np.shape
    r_hat_np = np.zeros((num_users, num_items))

    for user in range(num_users):
        for item in range(num_items):
            # Call a function that needs to be vectorized as much as possible
            r_hat_np[user, item], no = predict_rating_np(U_np, V_np, Y_np, user, item, w_item_np, B_il_np, c_lj_np, latent_factor, K)
            
    return r_hat_np

rate_hat = predict_all_ratings_np(ratings_np, U_np, V_np, Y_np, w_item_np, B_il_np, c_lj_np, latent_factor, K)
rate_hat_df = pd.DataFrame(rate_hat, index= UI_mat.index, columns= UI_mat.columns)
rate_hat_df.to_excel('SVD++_predic_100loop.xlsx')




### 2.3

In [3]:
import logging
from logging import getLogger
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.model.general_recommender import FISM
from recbole.trainer import Trainer
from recbole.utils import init_seed, init_logger
from recbole.utils.case_study import full_sort_topk
from recbole.model.general_recommender import SLIMElastic


#### SLIM

In [ ]:
config = Config(model='SLIMElastic', dataset='icheers', config_file_list = ['/home/r12323007/work_icheers/2024june/my_dataset.yaml'])
dataset = create_dataset(config)
init_logger(config)
logger = getLogger()
logger.info(dataset)
# dataset splitting
train_data, valid_data, test_data = data_preparation(config, dataset)
model = SLIMElastic(config, train_data.dataset)
trainer = Trainer(config, model)
best_valid_score, best_valid_result = trainer.fit(train_data, valid_data)
test_result = trainer.evaluate(test_data)
logger.info(test_result)

In [ ]:
import torch
from recbole.quick_start import load_data_and_model
from recbole.utils.case_study import full_sort_topk, full_sort_scores
from recbole.data.interaction import Interaction

config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
    model_file='/home/r12323007/work_icheers/2024june/saved/SLIMElastic-Jul-17-2024_21-46-21.pth'
)

In [9]:
picked_user_list = ['231228b77124b1331fbee2abfc9cf923', 'afb8a6cf419846dccdaca13bb275de65', '3b9abfef5b9dbfd31c664470dc528319',
                     'b1f7077b077152c4f004c7180a59c2e8', 'a789b30e0893ab3d4fcdceb18e46a782', '723b7787cb8db4e2d5ff7dee3af65a49']
uid_field = dataset.uid_field
uid_series = dataset.token2id(uid_field, picked_user_list)

topk_scores, topk_item_ids = full_sort_topk(
    uid_series, model, test_data, k=10, device=config["device"]
)

print(topk_scores)

item_field = dataset.iid_field
topk_external_item_ids = dataset.id2token(item_field, topk_item_ids)

print(topk_external_item_ids)

tensor([[0.0516, 0.0434, 0.0415, 0.0413, 0.0340, 0.0289, 0.0217, 0.0208, 0.0186,
         0.0174],
        [0.2093, 0.2069, 0.1458, 0.0990, 0.0809, 0.0757, 0.0676, 0.0637, 0.0591,
         0.0529],
        [0.0272, 0.0109, 0.0089, 0.0075, 0.0066, 0.0063, 0.0057, 0.0054, 0.0054,
         0.0031],
        [0.1213, 0.1137, 0.1117, 0.0908, 0.0812, 0.0784, 0.0777, 0.0704, 0.0647,
         0.0642],
        [0.1449, 0.1157, 0.1089, 0.0867, 0.0838, 0.0808, 0.0689, 0.0631, 0.0594,
         0.0592],
        [0.0386, 0.0372, 0.0220, 0.0202, 0.0193, 0.0188, 0.0177, 0.0170, 0.0140,
         0.0132]])
[['法國布根地_白' '法國布根地夜丘紅' '法國布根地伯恩丘紅' '美國加州北海岸紅' '法國香檳_白' '紐西蘭馬爾堡_白'
  '義大利托斯卡尼_紅' '法國布根地馬貢白' '法國波爾多_紅' '法國隆河谷_紅']
 ['法國波爾多聖愛斯臺夫紅' '義大利托斯卡尼_紅' '紐西蘭馬爾堡_白' '法國隆河谷教皇新堡紅' '法國香檳_粉紅' '法國薄酒萊_紅'
  '義大利皮蒙巴巴瑞斯科紅' '美國加州中部海岸紅' '阿根廷門多薩_紅' '法國波爾多玻美侯紅']
 ['美國加州北海岸紅' '紐西蘭馬爾堡_白' '法國布根地_白' '法國香檳_白' '義大利托斯卡尼_紅' '法國布根地夏布利白'
  '法國布根地夜丘紅' '法國布根地馬貢白' '法國布根地伯恩丘紅' '澳洲南澳巴羅沙谷紅']
 ['法國香檳_白' '法國布根地_紅' '法國布根地夜丘紅' '澳洲南澳巴羅沙谷紅' '法國波爾多波雅克

### Another SLIM model

In [32]:
import numpy as np
from sklearn.linear_model import ElasticNet

def train_slim_model(data, alpha=0.1, l1_ratio=0.5):
    """
    Train a SLIM model using ElasticNet.
    
    :param data: The user-item interaction matrix (numpy array).
    :param alpha: Regularization strength.
    :param l1_ratio: The ElasticNet mixing parameter, with 0 <= l1_ratio <= 1.
                     l1_ratio=0 corresponds to L2 penalty, l1_ratio=1 to L1 penalty.
    :return: A trained SLIM model (coefficients matrix).
    """
    # Number of items
    num_items = data.shape[1]
    
    # Model coefficients matrix
    W = np.zeros((num_items, num_items))
    
    # Train a model for each item
    for item in range(num_items):
        # Create target column
        y = data[:, item]
        
        # Create feature matrix
        X = np.delete(data, item, axis=1)
        
        # Define the model
        model = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, positive=True, fit_intercept=False, copy_X=True)
        
        # Fit the model
        model.fit(X, y)
        
        # Store the coefficients
        W[:, item] = np.insert(model.coef_, item, 0)
    
    return W

# Example data: User-item interaction matrix
data = np.array(UI_mat)
# Train the model
W = train_slim_model(data)
# Predict scores for all users
predicted_scores = np.dot(data, W)
predicted_SLIM_ratings = pd.DataFrame(predicted_scores, index= UI_mat.index,columns=UI_mat.columns)

Trained SLIM model coefficients:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [44]:
predicted_SLIM_ratings.to_csv('/home/r12323007/work_icheers/2024june/SLIM_model.csv')

#### FISM

In [ ]:
config = Config(model='FISM', dataset='icheers', config_file_list = ['/home/r12323007/work_icheers/2024june/my_dataset.yaml'])
dataset = create_dataset(config)
init_logger(config)
logger = getLogger()
logger.info(dataset)
# dataset splitting
train_data, valid_data, test_data = data_preparation(config, dataset)
model = FISM(config, train_data.dataset)
trainer = Trainer(config, model)
best_valid_score, best_valid_result = trainer.fit(train_data, valid_data)

test_result = trainer.evaluate(test_data)
logger.info(test_result)

In [ ]:
import torch
from recbole.quick_start import load_data_and_model
from recbole.utils.case_study import full_sort_topk, full_sort_scores
from recbole.data.interaction import Interaction

config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
    model_file='/home/r12323007/work_icheers/2024june/saved/FISM-Jul-17-2024_21-53-26.pth'
)

In [48]:
picked_user_list = ['231228b77124b1331fbee2abfc9cf923', 'afb8a6cf419846dccdaca13bb275de65', '3b9abfef5b9dbfd31c664470dc528319',
                     'b1f7077b077152c4f004c7180a59c2e8', 'a789b30e0893ab3d4fcdceb18e46a782', '723b7787cb8db4e2d5ff7dee3af65a49']
uid_field = dataset.uid_field
uid_series = dataset.token2id(uid_field, picked_user_list)

topk_scores, topk_item_ids = full_sort_topk(
    uid_series, model, test_data, k=10, device=config["device"]
)

print(topk_scores)

item_field = dataset.iid_field
topk_external_item_ids = dataset.id2token(item_field, topk_item_ids)

print(topk_external_item_ids)

tensor([[0.6814, 0.6773, 0.6771, 0.6642, 0.6623, 0.6623, 0.6610, 0.6600, 0.6581,
         0.6529],
        [0.3043, 0.3030, 0.3019, 0.2948, 0.2791, 0.2515, 0.2451, 0.2406, 0.2344,
         0.2324],
        [0.6240, 0.6199, 0.6197, 0.6089, 0.6068, 0.6050, 0.6050, 0.6036, 0.6026,
         0.6007],
        [0.3431, 0.3390, 0.3280, 0.3259, 0.3228, 0.3217, 0.3198, 0.3144, 0.3091,
         0.3091],
        [0.3548, 0.3509, 0.3509, 0.3496, 0.3412, 0.3257, 0.3241, 0.3145, 0.3123,
         0.3070],
        [0.5136, 0.5095, 0.5093, 0.4985, 0.4964, 0.4945, 0.4945, 0.4932, 0.4922,
         0.4903]])
[['法國香檳_白' '法國布根地夜丘紅' '美國加州北海岸紅' '法國波爾多波雅克紅' '法國布根地_白' '紐西蘭馬爾堡_白'
  '法國薄酒萊_紅' '法國波爾多聖愛斯臺夫紅' '法國布根地伯恩丘紅' '義大利托斯卡尼_紅']
 ['紐西蘭馬爾堡_白' '法國薄酒萊_紅' '法國波爾多聖愛斯臺夫紅' '義大利托斯卡尼_紅' '義大利皮蒙蜜思嘉達斯提白' '法國香檳_粉紅'
  '阿根廷門多薩_紅' '法國隆河谷教皇新堡紅' '日本甲信越地方山梨縣白' '義大利皮蒙巴巴瑞斯科紅']
 ['法國香檳_白' '法國布根地夜丘紅' '美國加州北海岸紅' '法國布根地_紅' '法國波爾多波雅克紅' '法國布根地_白'
  '紐西蘭馬爾堡_白' '法國薄酒萊_紅' '法國波爾多聖愛斯臺夫紅' '法國布根地伯恩丘紅']
 ['法國香檳_白' '法國布根地夜丘紅' '法國布根地_紅' '法國波爾多波雅克紅' 

### Another FISM model

In [54]:
import numpy as np

class FISM:
    def __init__(self, num_users, num_items, latent_dim=50, alpha=0.5, learning_rate=0.001, reg=0.1, epochs=20):
        self.num_users = num_users
        self.num_items = num_items
        self.latent_dim = latent_dim
        self.alpha = alpha
        self.learning_rate = learning_rate
        self.reg = reg
        self.epochs = epochs
        self.P = np.random.normal(scale=1.0/latent_dim, size=(num_items, latent_dim))
        self.Q = np.random.normal(scale=1.0/latent_dim, size=(num_items, latent_dim))

    def train(self, user_item_matrix):
        for epoch in range(self.epochs):
            for u in range(self.num_users):
                items_u = np.where(user_item_matrix[u, :] > 0)[0]
                if len(items_u) == 0:
                    continue
                for i in items_u:
                    item_set = set(items_u) - {i}
                    if len(item_set) == 0:
                        continue
                    q_i = self.Q[i]
                    p_u = np.sum(self.P[list(item_set)], axis=0) / (len(item_set) ** self.alpha)
                    if np.any(np.isnan(p_u)) or np.any(np.isnan(q_i)):
                        continue
                    error = user_item_matrix[u, i] - np.dot(p_u, q_i)
                    if np.isnan(error):
                        continue
                    self.Q[i] += self.learning_rate * (error * p_u - self.reg * q_i)
                    for j in item_set:
                        self.P[j] += self.learning_rate * (error * q_i / (len(item_set) ** self.alpha) - self.reg * self.P[j])
            print(f'Epoch {epoch + 1}/{self.epochs} completed.')

    def predict(self, user_item_matrix):
        predictions = np.zeros((self.num_users, self.num_items))
        for u in range(self.num_users):
            items_u = np.where(user_item_matrix[u, :] > 0)[0]
            if len(items_u) == 0:
                continue
            for i in range(self.num_items):
                item_set = set(items_u)
                if i in item_set:
                    item_set.remove(i)
                if len(item_set) == 0:
                    continue
                p_u = np.sum(self.P[list(item_set)], axis=0) / (len(item_set) ** self.alpha)
                if np.any(np.isnan(p_u)) or np.any(np.isnan(self.Q[i])):
                    predictions[u, i] = np.nan
                else:
                    predictions[u, i] = np.dot(p_u, self.Q[i])
        return predictions

user_item_matrix = np.array(UI_mat)

num_users, num_items = user_item_matrix.shape
fism = FISM(num_users, num_items)
fism.train(user_item_matrix)
predictions = fism.predict(user_item_matrix)

predicted_FISM_ratings = pd.DataFrame(predictions, index= UI_mat.index,columns=UI_mat.columns)

Epoch 1/20 completed.
Epoch 2/20 completed.
Epoch 3/20 completed.
Epoch 4/20 completed.
Epoch 5/20 completed.
Epoch 6/20 completed.
Epoch 7/20 completed.
Epoch 8/20 completed.
Epoch 9/20 completed.
Epoch 10/20 completed.
Epoch 11/20 completed.
Epoch 12/20 completed.
Epoch 13/20 completed.
Epoch 14/20 completed.
Epoch 15/20 completed.
Epoch 16/20 completed.
Epoch 17/20 completed.
Epoch 18/20 completed.
Epoch 19/20 completed.
Epoch 20/20 completed.


### LLORMA

In [52]:
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import svds
from sklearn.metrics.pairwise import cosine_similarity
from multiprocessing import Pool

def select_anchor_points(rating_matrix, num_anchors=3):
    num_users = rating_matrix.shape[0]
    return np.random.choice(num_users, num_anchors, replace=False)

def construct_submatrix(rating_matrix, anchor_point, threshold=0.5):
    user_sim = cosine_similarity(rating_matrix)
    similar_users = np.where(user_sim[anchor_point] > threshold)[0]
    submatrix = rating_matrix[similar_users]
    
    if submatrix.nnz == 0 or submatrix.shape[0] < 2 or submatrix.shape[1] < 2:
        return None, None
    return submatrix, similar_users

def decompose_matrix(rating_matrix, n_components=2):
    if n_components <= 0 or n_components >= min(rating_matrix.shape):
        n_components = min(rating_matrix.shape) - 1
    U, S, Vt = svds(rating_matrix, k=n_components)
    return U, np.diag(S), Vt

def predict_ratings(U, S, Vt):
    return np.dot(U, np.dot(S, Vt))

def process_anchor(rating_matrix, anchor, threshold, n_components):
    submatrix, similar_users = construct_submatrix(rating_matrix, anchor, threshold)
    if submatrix is not None and similar_users is not None:
        try:
            U, S, Vt = decompose_matrix(submatrix, n_components)
            submatrix_pred = predict_ratings(U, S, Vt)
            return submatrix_pred, similar_users
        except ValueError as e:
            return np.zeros(rating_matrix.shape), np.array([])
    return np.zeros(rating_matrix.shape), np.array([])

def llorma(rating_matrix, num_anchors=3, threshold=0.5, n_components=2):
    anchor_points = select_anchor_points(rating_matrix, num_anchors)
    predictions = np.zeros(rating_matrix.shape, dtype=float)
    weights = np.zeros(rating_matrix.shape, dtype=float)
    
    with Pool() as pool:
        results = pool.starmap(process_anchor, [(rating_matrix, anchor, threshold, n_components) for anchor in anchor_points])
    
    for submatrix_pred, similar_users in results:
        if len(similar_users) > 0:
            for i, user in enumerate(similar_users):
                for j in range(rating_matrix.shape[1]):
                    if rating_matrix[user, j] > 0:
                        predictions[user, j] += submatrix_pred[i, j]
                        weights[user, j] += 1
    
    final_predictions = np.divide(predictions, weights, out=np.zeros_like(predictions), where=weights != 0)
    return final_predictions

rating_matrix = csr_matrix(UI_mat.values)
print(rating_matrix.shape)
predicted_ratings = llorma(rating_matrix, num_anchors=50, threshold=0.2, n_components=100)
predicted_ratings_df = pd.DataFrame(predicted_ratings, index = UI_mat.index, columns= UI_mat.columns)

(10403, 738)


In [ ]:
predict_results(predicted_ratings_df)

231228b77124b1331fbee2abfc9cf923
這是預測的最高前10個
[('法國布根地 白', 4.978569218246232), ('法國布根地 紅', 0.9986796310555275), ('法國布根地夏布利白', 0.9896205647716101), ('美國加州北海岸白', 0.9825376892531215), ('阿根廷門多薩San Carlos紅', 0.0), ('阿根廷門多薩Santa Rosa紅', 0.0), ('阿根廷門多薩Tunuyan紅', 0.0), ('阿根廷門多薩Tupungato - Valle de Tupungato 白', 0.0), ('阿根廷門多薩烏格河谷白', 0.0), ('阿根廷門多薩烏格河谷紅', 0.0)]
這是原本最高的前10個
[('法國布根地 白', 5.0), ('法國布根地 紅', 1.0), ('法國布根地夏布利白', 1.0), ('美國加州北海岸白', 1.0)]


afb8a6cf419846dccdaca13bb275de65
這是預測的最高前10個
[('黎巴嫩  紅', 11.064970585240488), ('法國布根地 紅', 10.004847921550018), ('法國隆河谷隆河丘紅', 8.021680247982053), ('法國波爾多波雅克紅', 7.00998315357616), ('澳洲南澳巴羅沙谷紅', 7.0081089619808745), ('法國香檳 白', 6.999962196120359), ('西班牙利奧哈上利奧哈紅', 6.026312576827752), ('法國布根地上夜丘紅', 6.009095229769975), ('美國加州 白', 5.966814127804623), ('法國布根地 白', 5.009525406789947)]
這是原本最高的前10個
[('黎巴嫩  紅', 11.0), ('法國布根地 紅', 10.0), ('法國隆河谷隆河丘紅', 8.0), ('法國香檳 白', 7.0), ('澳洲南澳巴羅沙谷紅', 7.0), ('法國波爾多波雅克紅', 7.0), ('美國加州 白', 6.0), ('法國布根地上夜丘紅', 6.0), ('西班牙利奧哈上利奧哈紅',

In [ ]:
predicted_ratings_df.to_csv("/home/r12323007/work_icheers/2024june/LLORMA_model.csv")